# Generated by Django 3.2.5 on 2025-01-24 14:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='preferred_roles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='skills',
            field=models.TextField(default=datetime.datetime(2025, 1, 24, 14, 27, 17, 323618, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
